development:
  general_email: stevencarlanderson@gmail.com
  support_email: stevencarlanderson@gmail.com

test:
  general_email: stevencarlanderson@gmail.com
  support_email: stevencarlanderson@gmail.com

production:
  general_email: stevencarlanderson@gmail.com
  support_email: info@digitaltransgenderarchive.net
